### ISSUE TITLE
Support multiple cards per file?

### ISSUE THREAD

**Issue by domkm** [st3v3nmw/obsidian-spaced-repetition#20]
Hi Stephen,

First, thank you for providing such a useful plugin!

Second, would you consider supporting multiple cards per file? I know this may not be "Feynman-technique-esque" but smaller, more specific cards have their place as well. There is a [VSCode plugin called Recall](https://recall.frenya.net/) which does this and seems to work well. However, it would be preferable to not require multiple apps and also to be able to do mobile review. Would you consider expanding the scope of your plugin to include in-document cards?

**Comment by st3v3nmw** [comment]
Hello,

I could expand the scope to include that in future. I only have a problem with duplicating the work that has been done in Anki & Pseudonium's Obsidian_to_Anki which are very versatile.

This was also raised here: #12. Which got me thinking that we can split the type of reviews:  the current note-level & separate files for the flashcards. & for versatility, have the flashcards defined using regex à la Pseudonium's Obsidian_to_Anki.

I will put that on the roadmap, though it'll take a little while.
Thanks for the feedback.

**Comment by domkm** [comment]
That's wonderful!

One of the frustrating things with both of the current Obsidian plugins for Anki is that the cards can get out of sync, especially when trying to delete cards. I noticed in [a recent commit that you added a command for deletion](https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/23/files#diff-8fa4b52909f895e8cda060d2035234e0a42ca2c7d3f8f8de1b35a056537bf199R5). Is this necessary or might it be possible to diff the previously known cards with the current cards and automatically delete cached cards as appropriate? It seems to me that the ideal circumstance is that the Markdown files are the authoritative source for cards. Perhaps the `due`/`interval`/`ease` information could be included in the HTML comment in addition to or instead of an ID.

**Comment by st3v3nmw** [comment]
Hello,

Yes, I noticed that too. I had to reinstall the plugin and all scheduling data disappeared (hence the reason for reverting the 1.3.0 release). I'll make the change & have the scheduling information stored inside the Markdown files. The only downside is that we cannot support more complex card types such as cloze deletion without cluttering up the notes. Though that's a tradeoff I'm willing to make since there's no other way around it.
Thanks for your input.

**Comment by st3v3nmw** [comment]
Support for flashcards is now available on the latest release (v1.3.0). The scheduling information is stored inside the Markdown notes.
Card types:
1. Single line (`::` separator) i.e. 
```markdown
the question goes on this side::answer goes here!
```
2. Multiline (`?` separator) i.e.
```
As per the definition
of "multiline" the prompt
can be on multiple lines
?
same goes for
the answer
```

**Comment by domkm** [comment]
Well that was fast! Thanks!

I tested it briefly and think there are two small issues:
1. It doesn't seem to work for a file that is both a note and cards. Including tags for both types of review (or one tag if that tag is used for both types of review) results in only the full-note review.
2. The HTML tag is inserted under the `Q::A` line. This breaks lists. Could the HTML comment be appended to the same line as `Q::A`?

**Comment by st3v3nmw** [comment]
The first issue has been fixed in `1.3.1`.
For the second one, although it breaks the list in the editor view, it still renders the same in the preview. Plus, having the HTML comment on a separate line makes it not get in the way while editing.

Thanks for the Cloze formatting. I'll use that as the start, though I'll make it a little more compact.
The date format, I'll just let it be.

**Comment by st3v3nmw** [comment]
Yes, I'll provide a setting for that.

**Comment by domkm** [comment]
Thank you!

**Comment by ShreyasKallingal** [comment]
I wish I read this thread before posting #29! I would also really appreciate such an option.

**Comment by st3v3nmw** [comment]
Since the only outstanding issue is the lists & HTML comment thing, I'd like to close this & track that issue on #29.
