### ISSUE TITLE
[BUG] line break CRLF causes card missing and don't update date data

### ISSUE THREAD

**Issue by qiaogaojian** [st3v3nmw/obsidian-spaced-repetition#452]
My computer os is windows10, I found that line break CRLF could cause card missing and couldn't update the date data. I have fixed the bug temporarily by modify the compressed code in the plugins folder. Hoping this bug can be fixed officially.  
![image](https://user-images.githubusercontent.com/22113252/172021725-483cb920-497c-4738-a944-8446e910c9b7.png)
![image](https://user-images.githubusercontent.com/22113252/172021740-de2c8d38-bcec-49f5-9a14-8c83e890b7e1.png)

**Comment by ronzulu** [comment]
Hi @qiaogaojian 

Much of the code has been reworked since you posted the issue.

Although your fixes weren't specifically used, I expect that new releases would not have the problem you describe.

Personally I'm also on Windows 10, and don't have these issues.

Let us know if this is still an issue for you.

Cheers
Ronny

**Comment by ronzulu** [comment]
It appears that this has been resolved, so I'll close this now.

Feel free to reopen if this is still an issue.

Cheers
Ronny
