### ISSUE TITLE
[BUG] Cards wont reopen for review once they have been marked as Easy, Good or Hard.

### ISSUE THREAD

**Issue by MuffinOnTheRocks** [st3v3nmw/obsidian-spaced-repetition#762]
**Describe the bug**
[BUG] Cards wont reopen for review once they have been marked as Easy, Good or Hard.
All cards appear in the red (Hard) box and only newly added cards can be reviewed once, before they as well will not open again.

**To Reproduce**

1. Add new card
2. Review card and use Easy, Good or Hard
3. Try to reopen card again for review
4. Card won't open

**Comment by ronzulu** [comment]
Hi there

I recently made a couple of mistakes in some code I contributed:
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/759
https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/760

I have fixed these, and am doing more testing.

However, I'm not sure that the issue you experience is necessarily a bug. It's by design that cards that have been reviewed cannot be reviewed again until the determined interval (which might be initially days, and then later weeks or months) have elapsed.

However, there is a mechanism for reviewing these cards regardless of whether or not the programmatically determined "next review date" has been reached. This is known as "cramming", and this can be accessed by going into obsidian, selecting "open command palette", entering "spaced" and selecting one of the "cram" commands.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/547ff32d-e37c-45ab-b064-b016ad1cb0d4)

Please let me know if you are a new user, or an existing user that recently upgraded to version 1.10.2, and believes there has been a change in behaviour.

Regards
Ronny

**Comment by MuffinOnTheRocks** [comment]
Hi Ronny,

thanks for you fast response and for contributing to such an amazing Plug-In!

You are completely right, and this is not a bug. I'm a new user and got confused.

Thanks and best regards!

**Comment by ronzulu** [comment]
No worries, glad it worked out :smiley:

If you could please close off this issue, that would be appreciated.

Cheers
Ronny
