### ISSUE TITLE
[BUG] Reviewing note as good makes new invalid metadata field

### ISSUE THREAD

**Issue by fedor-setkov** [st3v3nmw/obsidian-spaced-repetition#764]
**Describe the bug**
After pressing "review note as a good" next fields arise (see screenshot)

**To Reproduce**
1. "Press review as good"
2. see strange metadata tags

**Expected behavior**
I want to see some valid values

**Screenshots**
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/97602785/f5e59017-28d3-4323-9263-5120c4bd8792)

**Versions (please complete the following information):**

-   OS: Mac OS Version 13.5.2 (22G91)
-   Obsidian version: 1.4.16
-   Plugin version: 1.10.2
-   If on desktop, Installer version: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36'

**Comment by ronzulu** [comment]
Hi Fedor 

Unfortunately I couldn't reproduce this issue.

Could you please try the prior version of the plug-in: 1.10.1
https://github.com/st3v3nmw/obsidian-spaced-repetition/releases/tag/1.10.1

This involves manually copying the following files to the `.obsidian\plugins\obsidian-spaced-repetition ` folder within your vault.

(This is the folder path on Windows, I'd expect something similar on Mac, but I don't know).

Let us know if you still experience the issue with 1.10.1.

> @st3v3nmw I essentially didn't touch this part of the code, so I don't think this issue relates to my recent contributions.

Cheers
Ronny

**Comment by pfabri** [comment]
@fedor-setkov @ronzulu Unfortunately, I can too can confirm that this is now an issue. Never experienced it before the latest release. One further piece of information which seems to be relevant that this only happens on Notes that fall in the 'New' review category i.e. those, which haven't yet had a date/ease etc. associated with them.

**Comment by ronzulu** [comment]
Thanks, those are good clues. Seems like my doing!  I'll investigate shortly.

**Comment by pfabri** [comment]
@ronzulu Sure. I did some further testing, taking the following steps:
1.
   - A. Creating a new note adding some content to it and my 'note-review' tag or
   - B. Removing existing review property field from an existing note. Since I have no other plugins using properties the result was always a file without any properties at all.
2. Close all notes, then close Obsidian
3. Reopen Obsidian, click on the 'Note review' icon
4. Select the note appearing under 'New' within the review tab.
5. Right-click, select 'Review Note as Good'

I'm attaching two files:
1. _Understanding Electromagnetic Fields and Antenna Radiation.md_: this file consistently reproduces the bug following the test sequence outlined above
2. _Empty.Note.md_: this has never produced the error at all

It seems like one of those temperamental, hard to chase down bugs. 

[Understanding Electromagnetic Fields and Antenna Radiation.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13025005/Understanding.Electromagnetic.Fields.and.Antenna.Radiation.md)
[Empty Note.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13025007/Empty.Note.md)

**Comment by ronzulu** [comment]
@pfabri Thx for the detailed sequence and files.

Unfortunately I still can't reproduce the main issue, but I can reproduce the strange behavior of the note tree you described.

I checked that under 1.10.1, and the strange stuff happens there as well. So at least I didn't introduce that bug 🙂 

Although it does give me an idea… If the note tree is getting screwed up, then perhaps right clicking and selecting "review as good" on an invalid tree entry may be the cause of the error.

BTW: initially when I was trying to reproduce the error I was always right clicking on the tab for the file itself, and selecting "review as good", so thanks for telling me that the bug was happening when you are using the note review sidebar.

---

@fedor-setkov  Could you please describe this in more detail. 

> After pressing "review note as a good" next fields arise (see screenshot)

1. Have you set up a hotkey for command "Spaced Repetition: Review note as easy" and pressing the hotkey for it? 
2. Or right clicking on the tab for the obsidian note and selecting "Review: Easy"? 
3. Or right clicking on the item from the note tree in the sidebar?

**Comment by pfabri** [comment]
@ronzulu You're welcome.

> Although it does give me an idea… If the note tree is getting screwed up, then perhaps right clicking and selecting "review as good" on an invalid tree entry may be the cause of the error.

Good thinking, sounds plausible. But I don't think the tree entry is invalid. It may be compromised is some ways that are not obvious to me. But I've just did a test where I only have the `[Understanding Electromagnetic Fields and Antenna Radiation.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13025005/Understanding.Electromagnetic.Fields.and.Antenna.Radiation.md)` file as the only 'New' note for review i.e. this is the only entry in the tree under 'New'. When I left-click on it, it opens up the note correctly. But right-clicking and selecting the 'Review as Good' in the tree view still throws the same error. But I am not a code contributor in this project or any Obsidian project at all, so I cannot gauge if there can be other layers where the tree entry can be incorrect even if a left-click opens the correct note.

**Comment by SubZeroX** [comment]
Same is happening to me

**Comment by ronzulu** [comment]
Hey @pfabri, @SubZeroX, @fedor-setkov   

@SubZeroX thanks for the screen capture. 

It helped show that the problem isn't specific to when reviewing the note through the side bar and right clicking on the item.

Unfortunately I still can't reproduce this.

### Code

I've created a version of the plug-in that includes some logging, so hopefully that will assist track this down.

https://github.com/ronzulu/obsidian-spaced-repetition/tree/bug-note-review-invalid-metadata-764

[main.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13113737/main.zip)


### Capture Log Info

Press ctrl-shift-i to bring up the chrome developer panels, and review a note.

If the invalid frontmatter data appears, please take a screenshot e.g.:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/d0c9d6dd-0d35-41a8-81bc-43a70004e0ec)

**Comment by SubZeroX** [comment]
Hey @ronzulu. 

I've tried to install the files you specified, but nothing happens in the console.


https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/98b75d57-26a1-4315-8ae6-0f77c65e16d6

**Comment by ronzulu** [comment]
Hey @SubZeroX 

Thanks for trying, I just want to check the file version you have installed:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/f7e0050b-df44-4cb3-8612-ddd1b5d1aeaf)

Also, not sure if you know, but you would need to restart obsidian (or disable and then reenable the plug-in) for the different `main.js` to take effect.

Cheers
Ronny

**Comment by SubZeroX** [comment]
Hey @ronzulu 

In this specific note, it still happens.
[🧍 Jean Piaget.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13193127/Jean.Piaget.md)

Here is the video: 

https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/f149d08a-5523-4ec7-b54b-8ed9b1bf5cb9

And here is the printscreen: 
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/ea33ace2-1cdf-47e2-b689-114531a5d2ca)

**Comment by ronzulu** [comment]
Awesome @SubZeroX, that really helped.

I think I've fixed it. Please try this out.

[main.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13195688/main.zip)

If it doesn't help, there is more detailed logging in the specific area where the problem happens. So another screenshot of the console would be great.

Cheers
Ronny

**Comment by SubZeroX** [comment]
Hey @ronzulu, i've discovered the strangest thing.

Your solution works but with a condition: the note must have no images. I'm sending you the image so you can also emulate this behavior.

Image: 
![markdown-img-paste-20200711213732380](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/82938c79-0644-4afe-8f58-0ac12a883618)


Demonstration: https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/39a54d24-40cc-4600-9291-86e15238e3dd

**Comment by ronzulu** [comment]
Thanks once again @SubZeroX , very helpful

I should be able to fix the remaining issue, hopefully tomorrow.

Love the sound track BTW

**Comment by ronzulu** [comment]
Hi  @SubZeroX, ok I believe I've fixed the bug now.

Please test, thanks!  If it fails, please do your lovely screen video capture with lovely backing music 😄 

[main.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13226978/main.zip)

Cheers
Ronny

**Comment by SubZeroX** [comment]
Hey @ronzulu, it works perfectly.

Thanks for your work and time spended in this project, it's been helping me for almost 2 years now!

**Comment by pfabri** [comment]
@ronzulu @SubZeroX  Amazing work both of you. Yes, I completely agree Obsidian in itself was already a life changer for me, but this plugin put an extra spin on that. I chose to donate the same amount as I paid for Obsidian itself because that's how essential it has become to my day-to-day workflow. Wish I could also contribute code like @ronzulu (I can see you're also a donor), but I don't speak JS, only Python and C/C++.

Thank you

**Comment by pfabri** [comment]
@SubZeroX I think you've misspelled Nietzsche's name in your Vault. I'd be afraid to do that -- brings bad Karma :D

**Comment by ronzulu** [comment]
@pfabri actually I started my career (I don't want to say how long ago) in C/C++, and then C#. I've dabbled a little with JavaScript before, but this is the first serious bit of work in TypeScript.

Of course all the credit goes to @st3v3nmw, I've only been involved the last 2 or 3 months.

> @SubZeroX I think you've misspelled Nietzsche's name in your Vault. I'd be afraid to do that -- brings bad Karma :D

😄

**Comment by GulTion** [comment]
> Hi @SubZeroX, ok I believe I've fixed the bug now.

it's working ......................, thx

**Comment by SubZeroX** [comment]
Hi @ronzulu, unfortunately it's happening again. 

All notes with images that are reviewed as "Hard" show in ease NAN.

Here is the video:

https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/1c8e544e-1396-408f-86e4-c2b7b4dc735f


Here is the note:
[Fisiologia da alimentação.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/13366886/Fisiologia.da.alimentacao.md)

First image: 
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/10550e24-a861-49d2-951b-ec91d67fd4ef)

Second image: 
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/13406988/d4b483ac-9394-4099-89d3-8c29c96e1e24)

**Comment by ronzulu** [comment]
Hi  @SubZeroX 

I got a notification email from GitHub:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/e74cb5f8-10cc-4957-84eb-d17584c25bd8)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/51af08b1-f4e0-454f-a7f1-b48d0e823856)

But I can't see the message here on this #764 page.

I'm wondering which version you are using. There was an interim version that fixed the issue with sr-due and sr-interval but not with sr-ease.

The issue with sr-ease was fixed in the version that was included in the mainstream release 1.10.5.

The version you did the screen capture with shows the debug output (meaning that you aren't using 1.10.5), as debug was removed for the 1.10.5 release.

If this still an issue, please open a new issue.

Cheers
Ronny

**Comment by SubZeroX** [comment]
Hey @ronzulu 

In fact, I was using the version you've created for #776 and that was the problem. When you have some time, I look forward to a solution for this other bug.

Thx!
