### ISSUE TITLE
[BUG] LaTeX multi-line tag ('$$') converted to single-line ('$') on review of multi-line flashcard

### ISSUE THREAD

**Issue by cogsandsquigs** [st3v3nmw/obsidian-spaced-repetition#766]
**Describe the bug**

After review of a multi-line flashcard that contains multi-line LaTeX, the delimiting tags are converted to single-line LaTeX tags ('$$' to '$'). The delimiter for the multi-line flashcard does not seem to matter; I personally use 4 dashes ('----'), but 3 dashes ('---') or 3 question marks ('???') on my machine produced the same results.

**To Reproduce**

1. Create a multi-line flashcard with a delimiter of '----', '---', or '???' (others may work, but I have not tested any others yet).
2. Insert multi-line LaTeX into the flashcard at some point, with delimiting tags of '$$'.
3. Review the flashcard.
5. See that the delimiting tags of the LaTeX have changed from '$$' to '$'.

**Expected behavior**

LaTeX should not be changed upon review, but instead preserved as-is.

**Screenshots**

Video of the bug in action:

[video link](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/59457601/9a891b37-3e56-4da1-8a42-cc78e9ca9e2b)

**Versions (please complete the following information):**

-   OS: macOS Ventura 13.6.1 (22G213)
-   Obsidian version: v1.4.16
-   Plugin version: v1.10.2
-   Installer version: '5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36'

**Additional context**

I know that this problem was tackled in [this issue](https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/527), but it is not yet resolved for this case. I have not seen anyone else report a similar error, but maybe I haven't looked deep enough. Surely this should be common? The only reason why it isn't that I can think of is that something on my local machine is different enough to cause this error. But I don't know what.

**Comment by ronzulu** [comment]
Hi Ian

The problem hasn't been experienced widely yet because it has just appeared in the latest upgrade 1.10.2.

The underlying bug was already present in 1.10.1 in core code, evident (perhaps only) when using the edit flashcard modal.

I recently restructured and rationalised a fair portion of the code base which went into 1.10.2. In the rationalisation I modified the plug-in which now makes use of that core code when reviewing a card, not just when editing it.

You may wish to revert back to 1.10.1 until this is resolved.

Hopefully I'll be able to find/fix (although happy for anyone else to beat me to it)

Cheers
Ronny

**Comment by cogsandsquigs** [comment]
Thanks! I'll be sure to stay at 1.10.1 for now.

**Comment by ronzulu** [comment]
Hey @cogsandsquigs, this has been fixed in the latest update 1.10.4

When you get a chance would you please verify and close the issue if all ok.

Cheers
Ronny

**Comment by cogsandsquigs** [comment]
Sorry for the delay, but from my end, it seems to have been fixed. Thanks for the patch!

**Comment by ronzulu** [comment]
Great, and if you could close off the issue that would be hopeful.
