### ISSUE TITLE
[BUG] Creates unexpected Flashcard from table

### ISSUE THREAD

**Issue by 4Source** [st3v3nmw/obsidian-spaced-repetition#858]
**Describe the bug**
For me it creates a Flashcard from a table.

**To Reproduce**

I have no Idea. But I added the file to context.

**Expected behavior**
Not to create a flashcard out of my table

**Screenshots**
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/abb084a9-20dd-4f12-86d7-3aaa73ca20b7)
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/b808f910-165f-46b0-8271-f9d3e6ae805c)
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/38220764/1d4e77b5-d034-47dd-875d-28af5e0e1afc)

**Versions:**

-   OS: Win10
-   Obsidian version: v1.5.3
-   Plugin version: 1.11.0
-   Installer version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.4.16 Chrome/114.0.5735.289 Electron/25.8.1 Safari/537.36

**Additional context**
File: [Java.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14068772/Java.md)

**Comment by ronzulu** [comment]
Hi @4Source 

Thanks for sending through the `Java.md` file. The card doesn't appear when I try to reproduce. I assume this is because I have different settings to you.

Could you please send through your settings file, relative to your vault folder it should be:
 `.obsidian\plugins\obsidian-spaced-repetition\data.json`

Nothing in deck `flashcards/sem1/prog`:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/4f496c42-3600-415b-a76b-230b49a6be28)

Cheers
Ronny

**Comment by 4Source** [comment]
Sure forgot that.

[data.json](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14071773/data.json)

**Comment by ronzulu** [comment]
Thanks, I can reproduce the issue now.

**Comment by ronzulu** [comment]
Hi @4Source 

The issue is caused by the `==` within the table, and that being defined as a cloze delimiter.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/9de9b670-4967-4b75-b9a4-deeda3afbe1f)

I probably wouldn't classify this as a bug, but definitely very unexpected behavior from a user perspective.

Cheers
Ronny

**Comment by 4Source** [comment]
I've been wondering how the cloze delimiters actually work. I couldn't get it to work in my cards. But then I agree, it's definitely not a bug.

**Comment by 4Source** [comment]
I found a workaround if anybody has the same problem just include a ``\`` in between the cloze delimiters. The ``\``wont be displayed but block the cloze delimiter

```
| Colum | Colum | Colum |
| --- | --- | --- |
| =\= | Row | =\=  |
```

| Colum | Colum | Colum |
| --- | --- | --- |
| =\= | Row | =\=  |
