### ISSUE TITLE
[FEAT]how about move "reset" button aside "hard" button in card review

### ISSUE THREAD

**Issue by Newdea** [st3v3nmw/obsidian-spaced-repetition#877]
**Is your feature request related to a problem? Please describe.**
Current reset button is above card content, and hard/good/easy button is at the bottom. When we learn new card, if we don't know the answer, we may want to rate it as reset. But clicking reset is not as convenient as clicking the other three options

**Describe the solution you'd like**
move reset button aside hard button, 

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/9208450/441caad1-853d-42b0-a084-65624aa4dfc1)

**Additional context**

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/9208450/8d418713-8337-4a5c-bb82-524acad4d1fe)

**Comment by ronzulu** [comment]
Good idea. With the current layout, sometimes I simply click "hard" when I probably should be clicking "reset"

I'd probably suggest calling the button "wrong" rather than "reset" (or "again")
- "reset", Not great as the software resets the scheduling data, but that isn't obvious to a user
- "again", Not great as more is being done than just shown the card again

Regarding the button color, I think that red is probably the most appropriate. Perhaps change the color for "hard" to something else, e.g. orange

I think this would address one of the points of confusion raised in:
[can someone provide a more elaborate explainer on how Again & skip really works?](https://github.com/st3v3nmw/obsidian-spaced-repetition/discussions/864)

Hey @KyleKlus what do you think?

**Comment by KyleKlus** [comment]
I basically never click reset, unless I didn't learn for a bit and then the schedule can be off because of it.
So I don't really have an opinion on that.

Design wise, it would offset the nice color and button trinity a bit. 
It just looks a bit more visually pleasing that way.
- All good things come in threes -

I would ask @st3v3nmw how he intended the use of the reset button and then decide based on that.

**Comment by KyleKlus** [comment]
Maybe we could add it as a setting. It would work like this:
- It is off by default and the user has to opt-in so that the users can adjust the plugin to their learning strategy. 
- The function of the button would be that this card is either randomly but back into the session queue or that the card is just appended to the session queue, such that it will resurface at the end of the session.

**Comment by Newdea** [comment]
I've been trying it out for a while, but found that I don't use it very often. So just keep it three is good, if want reset, use Reset on the menu.
