### ISSUE TITLE
[BUG] Keeps regurgitating the same index cards without updating them

### ISSUE THREAD

**Issue by nstebbins** [st3v3nmw/obsidian-spaced-repetition#890]
**Describe the bug**

So I've noticed that for certain Obsidian pages or more specifically Q&A pairs I create that it doesn't actually process when I review it. This causes that same Q&A to show up every day when I go to spaced repetition.

I have provided a screen recording of a particular instance for which this happens 'Syndication'. You can't see it but when I'm going through and reviewing all of the questions, I'm clicking "3" for good so it shouldn't show up anymore. And yet pretty much all the Q&A pairs including "Syndication" do show up over & over. 

**To Reproduce**

1. Add a particular note like the one that I specified below for 'Syndication'
2. Open spaced repetition and review it
3. Closed space repetition
4. Open it again and you'll be prompted with the same note

**Expected behavior**

I expect for every card that I reviewed today to not show up today again since it has already been reviewed. 

**Screenshots**

The screen recording was too big so I will attach it as a Drive link: https://drive.google.com/file/d/1d8dLa4R-X8V3Sb_yg1mJJ9-TYcUo9uSY/view?usp=drive_link. 

**Versions (please complete the following information):**

-   OS: [e.g. iOS] MacOS Sonoma 14.1.2
-   Obsidian version: [e.g. v0.12.4] 1.4.16
-   Plugin version: [e.g. v1.4.9] v1.10.5
-   If on desktop, Installer version: [run `this.navigator.appVersion` on the developer console, e.g. `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.12.3 Chrome/89.0.4389.128 Electron/12.0.6 Safari/537.36"`]

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

By the way in case you want the raw markdown of that particular file that I discussed in the screen recording, here it is. 
[Syndication.md](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14469421/Syndication.md)

----

Thank you for taking the time to read this! If you are able to assist me, I will speak quite highly of this plugin in r/ObsidianMD 😄

**Comment by ronzulu** [comment]
Hey Noah, thanks for the comprehensive issue description.

I'm pretty sure the problem was fixed in the latest release - likely related to leading and/or trailing spaces

With the latest version...

Initial state:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/960e2cc5-d5c1-4199-ae7e-68346f7094eb)

Reviewing:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/25cebb92-8cdf-4114-9198-ce8b4ce6caad)

Post review - html comment correctly added with schedule info:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/211a7230-c566-4ee3-a035-d01fcb49333c)

Card not longer shows up for review:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/6f5bccd6-6814-403d-878c-fac2f18ece58)

Hopefully you just need to upgrade to the latest release. Let me know how it goes.

Cheers
Ronny

**Comment by nstebbins** [comment]
Yep! Thanks! I just upgraded my plugin version and it looks good now. 

Cheers, 🍻 
Noah
