### ISSUE TITLE
[BUG] Very slow load of flashcard modal (since 1.11.2)

### ISSUE THREAD

**Issue by bgreenawald** [st3v3nmw/obsidian-spaced-repetition#914]
**Describe the bug**
Extremely sluggish performance when loading the flashcard review modal. I will click the "Review Flashcards" button and nothing will happen. After ~30 seconds, the review flashcards modal will finally pop up. The issue occurs on the most recent versions of the plugin on both Windows Desktop and Android. This seems related either to the most recent plugin version or the most recent Obsidian version as 2 days ago things were working fine.

**Versions (please complete the following information):**

-   OS: Windows 11, Android
-   Obsidian version: 1.5.11
-   Plugin version: 1.12.1
-   If on desktop, Installer version: 1.4.13

**Comment by jharst** [comment]
I'm experiencing the same issue on a MacBook Pro (MacOS 13.04.1) after the most recent update.
Versions:

- OS: Catalina 13.04.1
- Obsidian version: 1.5.11
- Plugin Version: 1.12.1
- Installer version: 1.4.14

What is more, on my iPhone the flashcard review modal won't show up at all. 

Versions:
- iOS 17.4.1
- Obsidian: 1.5.11
- Plugin version: 1.12.1

**Comment by 19031988** [comment]
I have the same issue. 

OS: Windows 10, Android 13
Obsidian version: 1.5.11
Plugin version: 1.12.1
If on desktop, Installer version: 1.5.11

**Comment by ronzulu** [comment]
I've always experienced times when there are very slow load times, i.e. prior to recent upgrades of either Obsidian or the plugin.

I haven't paid too much attention, but I'm quite sure this has happened for either:
- When plugin first loads
- When showing the flashcard review deck selection tree

Sometimes with load times probably of the order of 30 seconds.

When the plugin first loads, or when opening the flashcard review deck selection tree, the plugin iterates through every note in the vault to find flashcards. This overall process hasn't changed.

If you turn on logging, the actual load times will be available through the chrome debugger tools (ctrl-shift-i)

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/45f96faa-2401-4682-89d9-dc88785e88a6)

My vault has about 3000 markdown files, load times on Windows 10 Desktop using 1.12.1 are:

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/5c4e2f4d-bfe1-434a-a444-94bcaebffbef)

**Comment by ronzulu** [comment]
Thanks @bgreenawald for summarizing that so clearly.

I'll look into it in the next few days...

**Comment by 19031988** [comment]
> I turned on logging and tested a few loads using the previous and current versions of the plugin, both with the current version of Obsidian. This was on my Windows 11 PC.
> 
> **Plugin Version 1.11.2**
> 
> 1. SR: Sync took 1496ms
> 2. SR: Sync took 1123ms
> 3. SR: Sync took 1080ms
> 
> **Plugin Version 1.12.2**
> 
> 1. SR: Sync took 22449ms
> 2. SR: Sync took 23439ms
> 3. SR: Sync took 21797ms

dear @bgreenawald, could You explain how to switch the plugin to old version?

**Comment by bgreenawald** [comment]
@19031988 I used the BRAT plugin (https://github.com/TfTHacker/obsidian42-brat) which lets you load plugins from Github and pointed it to the 1.11.2 release.

**Comment by ronzulu** [comment]
Hi there

To implement enhancements for 1.12, I needed to make use of a different Obsidian API for obtaining tags. This likely is the cause of the slow down.

I have reverted the code to use the API that was originally used, but because I personally didn't experience the slow down, I can't test myself.

Could you please try...

There is a file called `main.js` in this zip file
[main_914A.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14803236/main_914A.zip)

You will need to copy that to the obsidian plug-in folder, e.g.
`D:\Obsidian\.obsidian\plugins\obsidian-spaced-repetition`

Then reload the plug-in, or restart obsidian. 

There is some extra debug. This might give a clue about the reason for our different experiences.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/cd0916e9-65ba-45ef-9c22-e1a056ecb3e1)


Ronny

**Comment by 19031988** [comment]
dear @ronzulu . I used a file from your zip.
But the behavior of my application has not changed:
- note tree loading is very slow when Obsidian is first started too;
- command showing the next note to repeat freezes on the PC;
- the same command showing the next note to repeat does not work at all on Android.

**Comment by ronzulu** [comment]
Hi @19031988 thanks for trying that out

Could you please send through a screenshot from the developer console.

- Restart Obsidian
- Within Obsidian press Ctrl-Shift-I - the developer tools should appear
- click on "console" and 
- take a screenshot - I'm after everything

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/0b212da6-1eea-4860-9870-5476b8d1ba36)

Thanks
Ronny

**Comment by 19031988** [comment]
dear @ronzulu here You are
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/51941668/e33aa741-2242-4cd8-985b-267455165667)

**Comment by ronzulu** [comment]
Dear @19031988 

Sorry, I forgot to mention one thing.

Before taking the screenshot, wait for the status bar to display the plugin's info:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/c6529a8b-43d0-45db-a5bb-59b6d5a246b7)

Then after that, click on the flashcard icon, and wait for the flashcard tree to be displayed.

Then take the screenshot like you did earlier.

And happy birthday for a couple of weeks ago :-)

Cheers
Ronny

**Comment by 19031988** [comment]
dear @ronzulu here You are again. And the greatest thanks for happy-birthday-words )
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/51941668/60e75328-d19d-4636-bc82-907f1d0d07d9)

**Comment by bgreenawald** [comment]
I'm getting similar results with the new beta. See screenshot below (this is all I could capture in a single screenshot but nothing else in the console seemed particularly relevant):

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/8428972/11d93075-440f-4661-bed8-05fb306c529a)

**Comment by ronzulu** [comment]
Hi again

I've come up with a new version which logs quite detailed timing info. It doesn't fix the problem, but hopefully will give me enough info to identify the problem.

Could you please try this out:
[main_914B.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14865363/main_914B.zip)

After restarting Obsidian (or reloading the plugin), wait for the initial load to complete, i.e. when the status bar shows the plugin info:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/c6529a8b-43d0-45db-a5bb-59b6d5a246b7)

From the developer console, you should see something like:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/bd1135ad-d962-45da-97f3-c5108da0591e)

Because there is so much info, save the log to a file, right-click:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/39a57d18-ef1a-48e9-8dd8-2e2cef2451ea)

And post the file to me.

Cheers
Ronny

**Comment by 19031988** [comment]
@ronzulu here you are. Great that you don't give up)
[obsidian.md-1712426543860.log](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14894504/obsidian.md-1712426543860.log)

**Comment by ronzulu** [comment]
Hi @19031988 thanks for that (and the encouragement)

I've updated `main.js` in the post above (now `main_914C.zip`), and added a note regarding clicking on "show more..."

If you could please try the new version with extra logging, and post the log file, that would be appreciated.

Cheers
Ronny

**Comment by 19031988** [comment]
@ronzulu here you are the updated log. It is exciting how is deep this rabbit hole )
[obsidian.md-1712489190423.log](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14896964/obsidian.md-1712489190423.log)

**Comment by jharst** [comment]
Hi @ronzulu 

For what it's worth, I also attach a log of the plugin's performance on my system. I do appreciate your looking into this issue!

Cheers 
Joachim
[obsidian.md-1712489672963.log](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14896975/obsidian.md-1712489672963.log)

**Comment by ronzulu** [comment]
Hi @19031988 

Thanks for that. for some reason the last few lines from the log wasn't saved (the highlighted lines shown below).

If you still have that session open, a screenshot would be great:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/6f793a59-c223-409e-b763-5bd9ed3f4c47)

Otherwise, please go through the process again, save the log and take a screenshot of the last page of the debug outlook.

The log file and screenshot must be from the same session.

Thanks
Ronny

**Comment by ronzulu** [comment]
Hi @jharst , thanks for sending that through.

Strange though - it seems to be with an older version. Can you please redo with the `main_914C.zip` above.

In the log it should say "C3":
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/c5a323a3-86ad-4ab8-a1d6-9ef7b09f3b61)

Also, please take a screenshot (same as for @19031988 in the previous post).

Cheers
Ronny

**Comment by jharst** [comment]
I'm sorry I missed the new version. Here is my log and a screenshot as requested!

[obsidian.md-1712491719594.log](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14897083/obsidian.md-1712491719594.log)

<img width="402" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/122213379/843db945-790f-4f88-a2e7-65c562c4c059">

**Comment by ronzulu** [comment]
Thanks @jharst @19031988 

I think I've fixed the issue, could you please try:
[main_914D.zip](https://github.com/st3v3nmw/obsidian-spaced-repetition/files/14897235/main_914D.zip)

If this hasn't worked, please send through the log file again.

Cheers
Ronny

**Comment by jharst** [comment]
Hi, Thanks again – this works very well for me and the load time is considerably shorter!

**Comment by 19031988** [comment]
dear @ronzulu ! Big yes it works! 
And as you may be remember on old version   showing random note didn't work on my mobile. 
And I tested this your D-version on mobile, and it works! Great thanks! 
You plugin is base, is fundamental instrument of my approach in job. With these freezes i was sad, so i am glad like shining toad now! )

**Comment by ronzulu** [comment]
Great, thanks @jharst @19031988 for all the back and forth diagnosing this!

@bgreenawald are you able to give this a test? Would be good if you can before I put in the PR.

**Comment by bgreenawald** [comment]
Hey @ronzulu

Unfortunately, my computer isn't letting me download the latest beta for some reason. It's triggering my anti-virus and completely blocking the download (I've never seen it do this before and don't know how to fix it). If you can upload the raw `main.js` file, I can give that a try.

Best,
Ben

**Comment by ronzulu** [comment]
Hi @bgreenawald Unfortunately GitHub won't late me upload a JavaScript file...

So I've put the zip file on dropbox, hopefully you can download:
https://www.dropbox.com/scl/fi/2dbi1v9mcnxxfglz20w04/main_914D.zip?rlkey=wskn5aewbi9594h9qljv0wh7f&dl=0

Cheers
Ronny

**Comment by bgreenawald** [comment]
The newest beta has ~5-second load times for me. Seems like the issue is largely resolved.

Best,
Ben
